### ISSUE TITLE
Fix pre/post plot for perception of tools covered.

### ISSUE THREAD

**Issue by kariljordan** [kariljordan/carpentry-community-assessment-projects#10]
In question 12 of the SWC [post-workshop survey](https://github.com/kariljordan/carpentry-community-assessment-projects/blob/master/software-carpentry-projects/survey-postworkshop.pdf) we ask about pre-workshop knowledge of the tools covered and pre-workshop perception of the tools covered. In question 13 we ask how their knowledge and perception changed. I would like to do a pre/post bar chart using the info in questions 12 and 13. The issue is that factor levels for the pre question isn't the same as the post question. Also, I don't want it to include the NAs.

This is the code I tried using this [code](https://github.com/kariljordan/carpentry-community-assessment-projects/blob/master/software-carpentry-projects/analysis-postworkshop.rmd):
knowledge_pre = c("Little or no knowledge of the topic", "Some knowledge of the topic", "Extensive knowledge of the topic")

knowledge_post = c("No increase in my knowledge", "Knowledge increased slightly", "Knowledge increased a little", "Knowledge increased a great deal", "N/A - Not 
covered at this workshop")

data$`Unix.Shell.Pre` <- 
  factor(data$`Unix.Shell.Pre``, 
         levels = knowledge_pre)

pre_and_post_knowledge <- 
data %>%
  select(`Unix.Shell.Pre`, 
          `Unix.Shell.Knowledge.Increase`) %>%
  gather() %>%
  group_by(key, value) %>%
  tally() %>%
  mutate( perc = 100 * (n/sum(n))) %>%
  filter(!is.na(key),
         !is.na(value)) 

  ggplot(pre_and_post_knowledge, 
         aes(x = factor(value, 
                        levels = programming), 
             y = perc, 
             fill = key)) +
    geom_bar(stat = "identity", 
             position = "dodge") +
    geom_text(aes(label=n), size= 4) +
    scale_x_discrete(labels = function(x) lapply(strwrap(x,
                                                         width = 10,
                                                         simplify = FALSE),
                                                 paste,
                                                 collapse = "\n")) +
    theme_classic() +
    xlab("Programming Usage") +
    ylab("% Respondents") +
    scale_fill_discrete(name = "",
                        labels = c("Before Workshop", "After Workshop")) +
    ggtitle("Respondents' Programming Knowledge Increased") +
    theme(plot.title = element_text(hjust = 0.5)) +
    theme_classic(base_size = 14)

**Comment by mkcor** [comment]
Hi @kariljordan !

I'm trying to run your report and get a feel for the data.

I commented out `levels = programming` because the variable `programming` does not seem to be defined.  When I run the code, the `pre_and_post_knowledge` dataframe I get has 9 rows and only one unique value for variable `key`:

```r
> unique(pre_and_post_knowledge$key)
[1] "Unix.Shell.Knowledge.Increase"
```

But that's the variable you are using for the `fill` aesthetic... so I believe we want two values, one that you label "Before Workshop" and the other "After Workshop"? Could you please clarify this for me? Thanks!

**Comment by benmarwick** [comment]
Yes, since the categories are slightly different for pre- and post-, we have to do two separate plots, then try to arrange then nicely with `grid.arrange`. 

The method below is quite nice because it uses `nest()` and `map()` which I think is a very tidy and elegant approach. 

The way we group the bars makes it clear that people generally started with little knowledge, and finished learning a lot, especially for Git, not so much for SQL


```
 knowledge_pre <-
    c(
    "Little or no knowledge of topic",
    "Some knowledge of topic",
    "Extensive knowledge of topic"
    )

knowledge_post <- 
  c("No increase in my knowledge", 
    "Knowledge increased slightly", 
    "Knowledge increased a little", 
    "Knowledge increased a great deal")

# let's compute for all tools...

# before the workshop
pre_knowledge <- 
data %>%
  select(contains("-Pre")) %>% 
  gather() %>% 
  filter(value %in% knowledge_pre) %>% 
  nest(-key) %>% 
  mutate(tallies = purrr::map(data, ~tally_and_perc(.x, value))) %>% 
  unnest(tallies) %>% 
  mutate(key = gsub("-Pre", "", key))

# after the workshop
post_knowledge <- 
data %>%
  select(contains("Knowledge-Increase")) %>% 
  gather() %>% 
  filter(value %in% knowledge_post) %>% 
  nest(-key) %>% 
  mutate(tallies = purrr::map(data, ~tally_and_perc(.x, value)))  %>% 
  unnest(tallies) %>% 
  mutate(key = gsub("-Knowledge-Increase", "", key))

# let's plot before and after as two grouped bar plots, then combine...

tools_before <- 
   ggplot(pre_knowledge, 
         aes(x = key,
             y = `%`,
             fill = fct_relevel(value, 
                             knowledge_pre))) +
    geom_col(position = "dodge") +
    geom_text(aes(label=n), 
              size= 4, 
              position=position_dodge(width=1)) +
    scale_x_discrete(labels = function(x) lapply(strwrap(x,
                                                         width = 10,
                                                         simplify = FALSE),
                                                 paste,
                                                 collapse = "\n")) +
    theme_classic() +
    xlab("") +
    ylab("% Respondents") +
    ggtitle("Knowledge before workshop") +
    theme(plot.title = element_text(hjust = 0.5)) +
    theme_classic(base_size = 14) +
    theme(legend.position = "bottom", 
          legend.title=element_blank()) 

tools_after <- 
   ggplot(post_knowledge, 
         aes(x = key,
             y = `%`,
             fill = fct_rev(fct_relevel(value, 
                             (knowledge_pre))))) +
    geom_col(position = "dodge") +
    geom_text(aes(label=n), 
              size= 4,
              position=position_dodge(width=1)) +
    scale_x_discrete(labels = function(x) lapply(strwrap(x,
                                                         width = 10,
                                                         simplify = FALSE),
                                                 paste,
                                                 collapse = "\n")) +
    theme_classic() +
    xlab("") +
    ylab("% Respondents") +
    ggtitle("Knowledge after workshop") +
    theme(plot.title = element_text(hjust = 0.5)) +
    theme_classic(base_size = 14) +
    theme(legend.position = "bottom", 
          legend.title=element_blank())
          
  
# put the two plots together
library(gridExtra)
grid.arrange(tools_before, 
             tools_after,
             ncol = 1)
```

![image](https://user-images.githubusercontent.com/1262179/27071445-5a4ae27a-5060-11e7-90fb-a28c364ccf56.png)

**Comment by kariljordan** [comment]
Thank you @mkcor for taking a look at the code! @benmarwick this is why I'm so proud to be a part of this community. I have never heard of grid.arrange. It's so nice to be able to explain what you want to do and get help doing it. This is exactly what I wanted!

**Comment by kariljordan** [comment]
@benmarwick when I try running this I receive this error:
Error: object 'value' not found

I'm wondering if I have all the packages I need. I get excited about this code and then can't run it LOL!

**Comment by maneesha** [comment]
@benmarwick said:

> The way we group the bars makes it clear that people generally started with little knowledge, and finished learning a lot, especially for Git, not so much for SQL

SQL is taught at very few SWC workshops, which probably accounts for some of this.  If SQL wasn't taught, we wouldn't expect knowledge to grow.
