### ISSUE TITLE
Combine multiple bar charts

### ISSUE THREAD

**Issue by kariljordan** [kariljordan/carpentry-community-assessment-projects#11]
In question 14 of the SWC [post workshop survey](https://github.com/kariljordan/carpentry-community-assessment-projects/blob/master/software-carpentry-projects/analysis-postworkshop.rmd) we ask respondents how their motivation to learn the tools that were covered in their workshop changed. Right now I'm doing one bar chart for each tool. How can I make one bar chart to include all the tools, and leave out the NAs?

Here is the [code](https://github.com/kariljordan/carpentry-community-assessment-projects/blob/master/software-carpentry-projects/analysis-postworkshop.rmd).

motivation = c("Less motivated", "Slightly less motivated", "No changes in motivation", "More motivated", "Much more motivated", "N/A - Topic not covered")
motivation = factor(motivation)

data$After.Unix.Shell.Motivation = factor(data$After.Unix.Shell.Motivation, levels = motivation)

data_motivation_tally <- 
  data %>% 
  group_by(After.Unix.Shell.Motivation) %>% 
  tally() %>% 
  filter(!is.na(After.Unix.Shell.Motivation)) 

ggplot(data_motivation_tally, 
         aes(After.Unix.Shell.Motivation, y = 100 * (n/sum(n)),
           n)) +
    geom_bar(stat = "identity", 
             position = "dodge", fill = "orange") +
    geom_text(aes(label=n), size= 4) +
    scale_x_discrete(labels = function(x) lapply(strwrap(x,
                                                         width = 10,
                                                         simplify = FALSE),
                                                 paste,
                                                 collapse = "\n")) +
    theme_classic() +
    xlab("Motivation Post-Workshop") +
    ylab("% Respondents") +
    ggtitle("Respondents' Motivation to Learn Unix Shell Increased") +
    theme(plot.title = element_text(hjust = 0.5)) +
    theme_classic(base_size = 14)

**Comment by benmarwick** [comment]
A grouped bar plot is one way to do it. Here's my attempt:

```
ordered_motiv <- 
  c("Less motivated",
    "Slightly less motivated",
     "No change in motivation",
    "More motivated",
    "Much more motivated")

# let's compute for all tools...

# motivation after the workshop
post_motivation <- 
data %>%
  select(grep("-Motivation", names(.))) %>% 
  gather() %>% 
  filter(value %in% ordered_motiv) %>% 
  nest(-key) %>% 
  mutate(tallies = purrr::map(data, ~tally_and_perc(.x, value))) %>% 
  unnest(tallies)  %>% 
  mutate(key = gsub("After-|-Motivation", "", key))
  
# let's plot ...

   ggplot(post_motivation, 
         aes(x = key,
             y = `%`,
             fill = fct_relevel(value, 
                             ordered_motiv))) +
    geom_col(position = "dodge") +
    scale_x_discrete(labels = function(x) lapply(strwrap(x,
                                                         width = 10,
                                                         simplify = FALSE),
                                                 paste,
                                                 collapse = "\n")) +
    theme_classic() +
    xlab("") +
    ylab("% Respondents") +
    ggtitle("Motivation after workshop") +
    theme(plot.title = element_text(hjust = 0.5)) +
    theme_classic(base_size = 14) +
    theme(legend.position = "bottom", 
          legend.title=element_blank()) +
    guides(fill=guide_legend(nrow=2,
                             byrow=TRUE)) 

```
![image](https://user-images.githubusercontent.com/1262179/27071734-656fe4a6-5061-11e7-8d1f-a73aeeecd261.png)

Looks like shell and SQL don't inspire people. That's certainly been my experience also! Both as an instructor and a user.

**Comment by jduckles** [comment]
Nice chart @benmarwick, I think the big thing to me is that we hardly de-motivate :) with anything.

**Comment by benmarwick** [comment]
Thanks! Yes, I agree, SWC/DC does not de-motivate!

**Comment by kariljordan** [comment]
@benmarwick Thank you so much for helping me with this chart. It makes so much sense.
