### ISSUE TITLE
Likert plot showing incorrect percentages

### ISSUE THREAD

**Issue by kariljordan** [kariljordan/carpentry-community-assessment-projects#5]
I'd like to know how to change the y axis labels on the likert plot. Also, the percentages on this plot are the exact same percentages from the long-term assessment survey l[ikert plot](https://github.com/carpentries/public-survey-info/issues/87). I copied and pasted the code thinking it would translate properly. Can someone find the bug and fix it? Code begins on line 125.

**Comment by benmarwick** [comment]
The easiest way is to change the column names on the data frame that goes into `likert()`. But there are some limitations, you can't have spaces, for example. 

Here's an example:

```
data <- readr::read_csv("https://raw.githubusercontent.com/kariljordan/carpentry-community-assessment-projects/master/software-carpentry-projects/public_swc_postworkshop_data_archivedJune2017.csv")


ordered_little <-
  c("Little or no knowledge of topic",
    "Some knowledge of topic",        
    "Extensive knowledge of topic") 

likert_cols_little <- 
 data %>% 
   select(which(map_lgl(data, ~`%in%`("Little or no knowledge of topic", .x)))) %>% 
   mutate_if(is.character, as.factor) %>% 
   mutate_all(funs(fct_relevel(., ordered_little))) %>% 
  filter_all(all_vars(!is.na(.))) 

# to relabel the y-axis, we can remove the '-Pre like this:"

names(likert_cols_little) <- gsub("-Pre", "", names(likert_cols_little) )

lc_little <- likert(data.frame(likert_cols_little))

# looks right!
plot(lc_little) +
  ggtitle("Self-Reported Knowledge of Tools Covered Pre-Workshop")

# let's double check the plot with a table:
xx <- 
likert_cols_little %>% 
  gather(key, value) %>% 
  group_by(key, value) %>% 
  tally() %>% 
  mutate(perc = round(n / sum(n) * 100, 1)) %>% 
  select(-n) %>% 
  spread(key, perc) %>% 
  slice(match(ordered_little,
              value))

# don't show the table in the report
## kable(xx)
```

![image](https://user-images.githubusercontent.com/1262179/27069535-96aa0604-5058-11e7-8864-2c8c17601d93.png)

**Comment by kariljordan** [comment]
Got it! I wonder how we can get rid of the periods in between the words in the column labels...I'm going to do some investigating.
