### ISSUE TITLE
Check code (Likert plot) to ensure all responses are included

### ISSUE THREAD

**Issue by kariljordan** [kariljordan/carpentry-community-assessment-projects#6]
Starting on line 172 there is a Likert plot for self-reported perception of workshop instructors/helpers. How do I change the y axis labels? Also, are we sure this plot is correct? Does it include all of the responses for each factor ("Never", "Rarely", "Sometimes", "Often", "All of the time")?

**Comment by benmarwick** [comment]
Here's my approach:

```

ordered_intim <-
  c("Not at all intimidating",
    "Not very intimidating",
    "Neither intimidating nor unintimidating",
    "Slightly intimidating to me",
    "Very intimidating to me",        
    "N/A or No opinion")  # again, yours doesn't match the data, 
# that maybe why your plot is wrong

likert_cols_intim <- 
 data %>% 
   select(which(map_lgl(data, ~`%in%`("Very intimidating to me", .x)))) %>% 
   mutate_if(is.character, as.factor) %>% 
   mutate_all(funs(fct_relevel(., ordered_intim))) %>% 
   filter_all(all_vars(!is.na(.)))  %>% 
   # drop the "N/A or No opinion" rows
   filter_all(all_vars(. != "N/A or No opinion"))  %>% 
   mutate_all(funs(fct_drop(., "N/A or No opinion"))) 

lc_intim <- likert(data.frame(likert_cols_intim))

# looks right!
plot(lc_intim) +
  ggtitle("Perception of Tools Covered Pre-Workshop")

# let's double check the plot with a table:
xx <- 
likert_cols_intim %>% 
  gather(key, value) %>% 
  group_by(key, value) %>% 
  tally() %>% 
  mutate(perc = round(n / sum(n) * 100, 1)) %>% 
  select(-n) %>% 
  spread(key, perc) %>% 
  slice(match(ordered_intim,
              value))

# don't show the table in the report
## kable(xx)
```

![image](https://user-images.githubusercontent.com/1262179/27069767-9e5ab5c8-5059-11e7-8030-ce250057b92d.png)

|value                                   |  Git| Python|    R|  SQL| Unix-Shell|
|:---------------------------------------|----:|------:|----:|----:|----------:|
|Not at all intimidating                 |  9.2|   11.9| 15.6| 11.5|       14.9|
|Not very intimidating                   | 10.5|   14.2| 15.4| 10.0|       15.3|
|Neither intimidating nor unintimidating | 23.5|   24.9| 24.4| 25.1|       21.3|
|Slightly intimidating to me             | 33.7|   26.1| 24.1| 27.5|       28.5|
|Very intimidating to me                 | 23.1|   22.9| 20.4| 26.0|       20.0|

**Comment by benmarwick** [comment]
Here's what I'd do for the plots on perception of instructors/helpers:

```

ordered_often <-
  c("Never", "Rarely", "Sometimes", "Often", "All of the time")

likert_cols_often_Inst <- 
 data %>% 
   select(grep("Instructors-", names(.))) %>% 
   mutate_if(is.character, as.factor) %>% 
   mutate_all(funs(fct_relevel(., ordered_often))) %>% 
   filter_all(all_vars(!is.na(.))) 
   
names(likert_cols_often_Inst) <- 
  gsub("Instructors-", "", names(likert_cols_often_Inst))
  
lc_often_inst <- likert(data.frame(likert_cols_often_Inst))

plot(lc_often_inst) +
  ggtitle("Instructors")

# to relabel the y-axis, see the previous chunk

# let's double check the plot with a table:
xx <- 
likert_cols_often_Inst %>% 
  gather(key, value) %>% 
  group_by(key, value) %>% 
  tally() %>% 
  mutate(perc = round(n / sum(n) * 100, 1)) %>% 
  select(-n) %>% 
  spread(key, perc) %>% 
  slice(match(ordered_often,
              value))

# don't show the table in the report
## kable(xx)
```

![image](https://user-images.githubusercontent.com/1262179/27070481-85690512-505c-11e7-8b7c-c0a896d0a7e8.png)

|value           | Clear-Answers| Communicators| Considerate| Enthusiastic|
|:---------------|-------------:|-------------:|-----------:|------------:|
|Never           |           0.2|           0.2|         0.1|          0.1|
|Rarely          |           0.4|           0.7|         0.2|          0.3|
|Sometimes       |           4.6|           8.8|         2.1|          3.4|
|Often           |          42.6|          36.3|        21.3|         25.4|
|All of the time |          52.2|          54.1|        76.4|         70.8|



```
# and now helpers

likert_cols_often_h <- 
 data %>% 
   select(grep("Helpers-", names(.))) %>% 
   mutate_if(is.character, as.factor) %>% 
   mutate_all(funs(fct_relevel(., ordered_often))) %>% 
   filter_all(all_vars(!is.na(.))) 
   
names(likert_cols_often_h) <- 
  gsub("Helpers-", "", names(likert_cols_often_h))
  
lc_often_h <- likert(data.frame(likert_cols_often_h))

plot(lc_often_h) +
  ggtitle("Helpers")

# to relabel the y-axis, see the previous chunk

# let's double check the plot with a table:
xx <- 
likert_cols_often_h %>% 
  gather(key, value) %>% 
  group_by(key, value) %>% 
  tally() %>% 
  mutate(perc = round(n / sum(n) * 100, 1)) %>% 
  select(-n) %>% 
  spread(key, perc) %>% 
  slice(match(ordered_often,
              value))

# don't show the table in the report
## kable(xx)

```

![image](https://user-images.githubusercontent.com/1262179/27070495-9b9dda74-505c-11e7-897c-b0f69f5b0ea4.png)


|value           | Clear-Answers| Communicators| Considerate| Enthusiastic|
|:---------------|-------------:|-------------:|-----------:|------------:|
|Never           |           0.2|           0.2|         0.2|          0.2|
|Rarely          |           0.4|           0.4|         0.1|          0.5|
|Sometimes       |           6.0|           5.2|         2.5|          5.0|
|Often           |          36.0|          30.2|        22.0|         25.4|
|All of the time |          57.4|          63.9|        75.3|         68.9|

**Comment by kariljordan** [comment]
It's so great to see that respondents speak highly of our instructors and helpers!
