### ISSUE TITLE
Likert plot for tools covered

### ISSUE THREAD

**Issue by kariljordan** [kariljordan/carpentry-community-assessment-projects#7]
Code starts on line 204. How do I change the y axis labels? Is there a better way to show this information?

**Comment by benmarwick** [comment]
Is this the section you're referring to? I can't see the line numbers on GitHub, and line 204 of [that Rmd](https://github.com/kariljordan/carpentry-community-assessment-projects/blob/master/software-carpentry-projects/analysis-postworkshop.rmd) in my RStudio is about perception of workshop instructors/helpers. Anyway, here's what I'd do for the likert plot on tools covered:

```

ordered_intim <-
  c("Not at all intimidating",
    "Not very intimidating",
    "Neither intimidating nor unintimidating",
    "Slightly intimidating to me",
    "Very intimidating to me",        
    "N/A or No opinion")  # again, yours doesn't match the data, 
# that maybe why your plot is wrong

likert_cols_intim <- 
 data %>% 
   select(which(map_lgl(data, ~`%in%`("Very intimidating to me", .x)))) %>% 
   mutate_if(is.character, as.factor) %>% 
   mutate_all(funs(fct_relevel(., ordered_intim))) %>% 
  filter_all(all_vars(!is.na(.)))  %>% 
  # drop the "N/A or No opinion" rows
  filter_all(all_vars(. != "N/A or No opinion"))  %>% 
  mutate_all(funs(fct_drop(., "N/A or No opinion"))) 

names(likert_cols_intim) <- gsub(".Perception", "", names(likert_cols_intim))

lc_intim <- likert(data.frame(likert_cols_intim))

# looks right!
plot(lc_intim) +
  ggtitle("Perception of Tools Covered Pre-Workshop")

# let's double check the plot with a table:
xx <- 
likert_cols_intim %>% 
  gather(key, value) %>% 
  group_by(key, value) %>% 
  tally() %>% 
  mutate(perc = round(n / sum(n) * 100, 1)) %>% 
  select(-n) %>% 
  spread(key, perc) %>% 
  slice(match(ordered_intim,
              value))

# don't show the table in the report
## kable(xx)
```

![image](https://user-images.githubusercontent.com/1262179/27070846-ffbb72fe-505d-11e7-8019-4dea87f5d72c.png)

|value                                   |  Git| Python|    R|  SQL| Unix-Shell|
|:---------------------------------------|----:|------:|----:|----:|----------:|
|Not at all intimidating                 |  9.2|   11.9| 15.6| 11.5|       14.9|
|Not very intimidating                   | 10.5|   14.2| 15.4| 10.0|       15.3|
|Neither intimidating nor unintimidating | 23.5|   24.9| 24.4| 25.1|       21.3|
|Slightly intimidating to me             | 33.7|   26.1| 24.1| 27.5|       28.5|
|Very intimidating to me                 | 23.1|   22.9| 20.4| 26.0|       20.0|

**Comment by kariljordan** [comment]
That is very helpful for me when I'm creating issues to know that you have to actually download the code to see the line numbers. Duh! I see what I did wrong. The table helps as well to confirm the plot is correct. THANK YOU BEN!
